name: Build and Test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

#    - name: Setup .NET Core 6
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: '6.0.x'
#        include-prerelease: true
#
#    - name: Setup dotnet Core 3.1
#      uses: actions/setup-dotnet@v1
#      with:
#        dotnet-version: '3.1.x'

    - name: Install dependencies
      run: dotnet restore -v:m
      
    - name: Build
      run: dotnet build -v:m --configuration Release --no-restore
    
    - name: Test
      run: dotnet test -v:m --no-restore --no-build --configuration Release