name: CI

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET Core Versions
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          6.0.x
          7.0.x
        include-prerelease: true

    - name: Install NuGet dependencies
      run: dotnet restore -v:m -p:GitHubCI=yes
      
    - name: Build
      run: dotnet build -v:m -c Release --no-restore -p:GitHubCI=yes
    
    - name: Test
      run: dotnet test -v:m -c Release --no-build -p:GitHubCI=yes

    - name: Pack
      if: runner.os == 'Windows'
      run: dotnet pack -v:m -c Release --no-build -p:GitHubCI=yes

    - name: Package nupkg files
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: nupkg-files
        path: nupkg/Release/*nupkg
